version: "3"
services:
  backend:
    build:
        context: server
        dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
        - ./server:/app
        - /app/node_modules/
    networks:
      - mern-app
  client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    environment:
      BACKEND_SERVICE_URL: http://backend:5000
    ports:
      - "80:80"
    volumes:
        - ./client:/app
        - /app/node_modules/
    stdin_open: true
    tty: true
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
